import type {Metadata} from 'next'
import {Inter, Oxanium, Roboto} from 'next/font/google'
import './globals.css'
import {ReactNode} from "react";
import Navigation from "@/components/Navigation/Navigation";
import CursorAnimation from "@/components/CursorAnimation/CursorAnimation";

const oxanium = Oxanium({
    weight: "500",
    subsets: ["latin"]
});

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }


interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
    return (
        <html lang="en">
        <head>
            <title>Portfolio</title>
        </head>
        <body className={oxanium.className}>
        <main>
            <CursorAnimation>
                <Navigation/>
                {props.children}
            </CursorAnimation>
        </main>
        </body>
        </html>
    )
}
