
export const experiences = [
    {
        title: "TEAM Mentor",
        type: "Tomlinson Engagement Award for Mentoring (TEAM) program",
        location: "McGill",
        image: "/assets/experience/mcgillLogo.png",
        description: "Teaching assistance for Digital Logic (ECSE-222). Host office hours answer questions about digital logic",
        width: 180,
        height: 75,
    },
    {
        title: "Developer",
        type: "Hackathon Project",
        location: "UoT",
        image: "/assets/experience/liaLogo-removebg-preview.png",
        description: "Lia : A Memory Aid Assistant (Project) Application to aid people with memory loss by interpreting questions and relaying answers back to the user using artifical intelligence. Won Best Health Hack at NewHacks 2021, University of Toronto.",
        github: "https://github.com/mattcab2002/Liassistant",
        width: 200,
        height: 200,
    },
    {
        title: "Full Stack Blockchain Developer",
        type: "Contract",
        location: "DDC NFT",
        image: "/assets/experience/nftlogo.png",
        description: "Developed a web application and smart contract for Dauntless Dolphins Club NFT. Learned about full stack web development, VueJs, NuxtJs, blockchain development and solidity.",
        width: 125,
        height: 125,
        link: "https://dauntlessdolphins.com"
    },
    {
        title: "Developer",
        type: "Hackathon Project",
        location: "Phizer",
        image: "/assets/experience/ai.png",
        description: "PharmaHacks 2022 (Project) Machine learning models to predict the diagnosis of disease based on presence of bacteria in the gut microbiome.",
        width: 150,
        height: 150,
    },
    {
        title: "Developer",
        type: "Hackathon Project",
        location: "McGill",
        image: "/assets/experience/pictodocreader.png",
        description: "PictoDocReader : A PDF Image Locator (Project). Full stack development of a software to locate images within PDFs. Won Best Education Hack at McHacks 9, McGill University.",
        github: "https://github.com/mattcab2002/PictoDocReader",
        width: 250,
        height: 175,
    },
    {
        title: "Web Developer",
        type: "Part-Time",
        location: "Voysis IP Solutions",
        image: "/assets/experience/voysisLogo.png",
        description: "Developped a web site for Voysis's new company GoingVoIP. Learned about web development, NextJs and React.",
        width: 180,
        height: 80,
    },
    {
        title: "Tech Lead & Event Organizer",
        type: "Volunteering",
        location: "GDSC at Mcgill",
        image: "/assets/experience/Dark Stacked Logo.png",
        description: "Proving guidance and mentorship to club members, fostering a collaborative learning environment. Leading hands-on projects, applying full stack of development skills and leveraging emerging technologies. Establishing connections with industry professionals and organzing guest speaker sessions to expose members to real-worls insights.",
        width: 180,
        height: 80,
    },
    {
        title: "Cybersecurity Intern",
        type: "Internship",
        location: "CGI",
        description: "Learned about Cyber security basics, security and access control models, IAM concepts and technologies, AWS IAM, Microsoft Azure, IAM automation, ethical hacking basics, sql and docker. Developed a service offer and a proof of concept for automating IAM processes.",
        image: "/assets/experience/CGILogo.png",
        width: 160,
        height: 80,
    },
    {
        title: "Full Stack Developer",
        type: "Internship",
        location: "Intact Financial Corporation",
        description: "Full stack development on enterprise applications, Spring, Angular, Jenkins, Oracle DB, Liquibase, SQL, Agile development.",
        image: "/assets/experience/Intact-Insurance-Alberta-Logo-big.webp",
        width: 160,
        height: 80,
    },
    {
        title: "Software Developer",
        type: "Internship",
        location: "Mirametrix / Lattice semiconductor",
        description: "Played a key role in maintaining the DevOps infrastructure. Utilized tools like Docker, Python, GitHub Actions, and Jenkins to develop build tools, pipelines and workflows. Contributed to the team's initiatives by actively developing new solutions and processes.",
        image: "/assets/experience/Lattice Semiconductor.webp",
        width: 160,
        height: 160,
    },
    {
        title: "Co-Founder and Developer",
        type: "Co-Founder",
        location: "Devpro",
        image: "/assets/experience/logo.png",
        description: "Co-founded Devpro, a sofwtare consulting and development company.",
        link: "https://www.devpromedia.com",
        width: 125,
        height: 125,
    },
];
